[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
viaIR = true
optimizer = true
optimizer_runs = 200
ffi = true
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
[dependencies]

[rpc_endpoints]
bera = "${RPC_URL_BERA}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
